# Generated by Django 5.2.8 on 2025-11-30 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sociallink_alter_userprofile_profile_pic_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='links',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Author', to='accounts.sociallink'),
        ),
    ]
