# Generated by Django 5.2.8 on 2025-11-30 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_author_links'),
        ('shop', '0005_alter_book_author_alter_book_century'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='century',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to='shop.century'),
        ),
        migrations.AlterField(
            model_name='author',
            name='links',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to='accounts.sociallink'),
        ),
    ]
