# Generated by Django 5.2.8 on 2025-11-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_register_alter_user_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='code',
            field=models.IntegerField(max_length=5),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone_number',
            field=models.CharField(),
        ),
    ]
