# Generated by Django 5.2.8 on 2025-12-01 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_author_slug_alter_author_century_alter_author_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='links',
        ),
        migrations.AddField(
            model_name='sociallink',
            name='author',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='accounts.author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
