# Generated by Django 5.2.8 on 2025-12-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_verifyemail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='sale',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('profile-completed', 'Profile Completed'), ('Active', 'Active')], default='inactive', max_length=30),
        ),
        migrations.AlterField(
            model_name='verifyemail',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
