# Generated by Django 5.2.8 on 2025-12-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_author_sale_alter_author_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='status',
            field=models.CharField(choices=[('Inactive', 'inactive'), ('Profile Completed', 'Profile-completed'), ('Active', 'Active')], default='inactive', max_length=30),
        ),
    ]
