# Generated by Django 5.2.8 on 2026-01-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_author_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='status',
            field=models.CharField(choices=[('Inactive', 'inactive'), ('Profile Completed', 'Profile-completed'), ('Active', 'Active')], default='Inactive', max_length=30),
        ),
    ]
