# Generated by Django 5.2.8 on 2025-12-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Public', 'Public'), ('Waiting', 'Waiting')], default='Public', max_length=20),
        ),
    ]
