# Generated by Django 5.2.8 on 2025-12-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comment_article_articleview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleview',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='articleview',
            name='session_key',
            field=models.CharField(db_index=True, max_length=40, null=True),
        ),
    ]
