# Generated by Django 5.2.8 on 2026-01-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Bookim', max_length=100)),
                ('facebook', models.URLField(blank=True, default='https://www.facebook.com', null=True)),
                ('twitter', models.URLField(blank=True, default='https://twitter.com', null=True)),
                ('instagram', models.URLField(blank=True, default='https://www.instagram.com/bookim', null=True)),
                ('linkedin', models.URLField(blank=True, default='https://www.linkedin.com', null=True)),
                ('telegram', models.URLField(blank=True, default='https://www.telegram.org/bookim', null=True)),
                ('email', models.EmailField(default='bookim.bookshop@gmail.com', max_length=254)),
            ],
        ),
    ]
