# Generated by Django 5.2.8 on 2026-01-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='twitter',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='x',
            field=models.URLField(blank=True, default='https://x.com', null=True),
        ),
    ]
