# Generated by Django 5.2.8 on 2025-12-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='books/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Shipped', 'Shipped'), ('Transmitted', 'Transmitted'), ('Canceled', 'Canceled'), ('Completed', 'Completed')], default='paid', max_length=30),
        ),
    ]
