# Generated by Django 5.2.8 on 2025-11-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_book_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='avg_rating',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
