# Generated by Django 5.2.8 on 2025-12-30 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_book_number_book_status_alter_book_century_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='century',
        ),
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='shop.category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='dimensions',
            field=models.CharField(max_length=300),
        ),
    ]
