# Generated by Django 5.2.8 on 2025-11-30 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sociallink_alter_userprofile_profile_pic_author'),
        ('shop', '0004_alter_book_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='century',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='shop.century'),
        ),
    ]
