# Generated by Django 5.2.8 on 2025-12-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_book_century_alter_book_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='dimensions',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='sku',
            field=models.CharField(max_length=40),
        ),
    ]
