# Generated by Django 5.2.8 on 2025-12-01 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_author_links_sociallink_author_and_more'),
        ('shop', '0005_alter_book_author_alter_book_century'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='accounts.author'),
        ),
    ]
