# Generated by Django 5.2.8 on 2025-12-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_author_status'),
        ('shop', '0006_remove_book_publish_date_book_century_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_authors',
            field=models.ManyToManyField(blank=True, to='accounts.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='dimensions',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
