# Generated by Django 5.2.8 on 2025-12-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_book_book_authors_alter_book_dimensions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_authors',
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='shop/books/cover/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
